Traceback (most recent call last):
  File "/home/shrihan/weaklens/gaia_match_psf/gaia_match_psf_code/src/gaiamatch_hscy3_i.py", line 48, in <module>
    des = read_hscy3_h5(PSF_DATA_FILEPATH, n = TOTAL_SUBSAMPLE_SIZE)
  File "/home/shrihan/weaklens/gaia_match_psf/gaia_match_psf_code/src/gaiamatch_hscy3_i.py", line 30, in read_hscy3_h5
    with h5.File(file_path, 'r') as f:
NameError: name 'h5' is not defined
